services:
  - type: web
    name: youtube-eng
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        fromService:
          type: web
          name: youtube-eng
          property: port

